// Code generated by go-swagger; DO NOT EDIT.

package graph

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// CreateGraphReader is a Reader for the CreateGraph structure.
type CreateGraphReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateGraphReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateGraphOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateGraphBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateGraphNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateGraphInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateGraphOK creates a CreateGraphOK with default headers values
func NewCreateGraphOK() *CreateGraphOK {
	return &CreateGraphOK{}
}

/* CreateGraphOK describes a response with status code 200, with default header values.

Ok
*/
type CreateGraphOK struct {
	Payload []*models.WithTaskGraph
}

func (o *CreateGraphOK) Error() string {
	return fmt.Sprintf("[POST /create-graph][%d] createGraphOK  %+v", 200, o.Payload)
}
func (o *CreateGraphOK) GetPayload() []*models.WithTaskGraph {
	return o.Payload
}

func (o *CreateGraphOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGraphBadRequest creates a CreateGraphBadRequest with default headers values
func NewCreateGraphBadRequest() *CreateGraphBadRequest {
	return &CreateGraphBadRequest{}
}

/* CreateGraphBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateGraphBadRequest struct {
	Payload *models.ErrorBody
}

func (o *CreateGraphBadRequest) Error() string {
	return fmt.Sprintf("[POST /create-graph][%d] createGraphBadRequest  %+v", 400, o.Payload)
}
func (o *CreateGraphBadRequest) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *CreateGraphBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGraphNotFound creates a CreateGraphNotFound with default headers values
func NewCreateGraphNotFound() *CreateGraphNotFound {
	return &CreateGraphNotFound{}
}

/* CreateGraphNotFound describes a response with status code 404, with default header values.

Not found
*/
type CreateGraphNotFound struct {
	Payload *models.ErrorBody
}

func (o *CreateGraphNotFound) Error() string {
	return fmt.Sprintf("[POST /create-graph][%d] createGraphNotFound  %+v", 404, o.Payload)
}
func (o *CreateGraphNotFound) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *CreateGraphNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateGraphInternalServerError creates a CreateGraphInternalServerError with default headers values
func NewCreateGraphInternalServerError() *CreateGraphInternalServerError {
	return &CreateGraphInternalServerError{}
}

/* CreateGraphInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type CreateGraphInternalServerError struct {
	Payload *models.ErrorBody
}

func (o *CreateGraphInternalServerError) Error() string {
	return fmt.Sprintf("[POST /create-graph][%d] createGraphInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateGraphInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *CreateGraphInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
