// Code generated by go-swagger; DO NOT EDIT.

package vlan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/models"
)

// CreateVMVlanReader is a Reader for the CreateVMVlan structure.
type CreateVMVlanReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateVMVlanReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateVMVlanOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateVMVlanBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateVMVlanOK creates a CreateVMVlanOK with default headers values
func NewCreateVMVlanOK() *CreateVMVlanOK {
	return &CreateVMVlanOK{}
}

/* CreateVMVlanOK describes a response with status code 200, with default header values.

Ok
*/
type CreateVMVlanOK struct {
	Payload []*models.WithTaskVlan
}

func (o *CreateVMVlanOK) Error() string {
	return fmt.Sprintf("[POST /create-vm-vlan][%d] createVmVlanOK  %+v", 200, o.Payload)
}
func (o *CreateVMVlanOK) GetPayload() []*models.WithTaskVlan {
	return o.Payload
}

func (o *CreateVMVlanOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateVMVlanBadRequest creates a CreateVMVlanBadRequest with default headers values
func NewCreateVMVlanBadRequest() *CreateVMVlanBadRequest {
	return &CreateVMVlanBadRequest{}
}

/* CreateVMVlanBadRequest describes a response with status code 400, with default header values.

CreateVMVlanBadRequest create Vm vlan bad request
*/
type CreateVMVlanBadRequest struct {
	Payload string
}

func (o *CreateVMVlanBadRequest) Error() string {
	return fmt.Sprintf("[POST /create-vm-vlan][%d] createVmVlanBadRequest  %+v", 400, o.Payload)
}
func (o *CreateVMVlanBadRequest) GetPayload() string {
	return o.Payload
}

func (o *CreateVMVlanBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
