// Code generated by go-swagger; DO NOT EDIT.

package vm_volume_snapshot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// NewCreateVMVolumeSnapshotParams creates a new CreateVMVolumeSnapshotParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateVMVolumeSnapshotParams() *CreateVMVolumeSnapshotParams {
	return &CreateVMVolumeSnapshotParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVMVolumeSnapshotParamsWithTimeout creates a new CreateVMVolumeSnapshotParams object
// with the ability to set a timeout on a request.
func NewCreateVMVolumeSnapshotParamsWithTimeout(timeout time.Duration) *CreateVMVolumeSnapshotParams {
	return &CreateVMVolumeSnapshotParams{
		timeout: timeout,
	}
}

// NewCreateVMVolumeSnapshotParamsWithContext creates a new CreateVMVolumeSnapshotParams object
// with the ability to set a context for a request.
func NewCreateVMVolumeSnapshotParamsWithContext(ctx context.Context) *CreateVMVolumeSnapshotParams {
	return &CreateVMVolumeSnapshotParams{
		Context: ctx,
	}
}

// NewCreateVMVolumeSnapshotParamsWithHTTPClient creates a new CreateVMVolumeSnapshotParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateVMVolumeSnapshotParamsWithHTTPClient(client *http.Client) *CreateVMVolumeSnapshotParams {
	return &CreateVMVolumeSnapshotParams{
		HTTPClient: client,
	}
}

/* CreateVMVolumeSnapshotParams contains all the parameters to send to the API endpoint
   for the create Vm volume snapshot operation.

   Typically these are written to a http.Request.
*/
type CreateVMVolumeSnapshotParams struct {

	// ContentLanguage.
	//
	// Default: "en-US"
	ContentLanguage *string

	// RequestBody.
	RequestBody []*models.VMVolumeSnapshotCreationParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create Vm volume snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMVolumeSnapshotParams) WithDefaults() *CreateVMVolumeSnapshotParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create Vm volume snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMVolumeSnapshotParams) SetDefaults() {
	var (
		contentLanguageDefault = string("en-US")
	)

	val := CreateVMVolumeSnapshotParams{
		ContentLanguage: &contentLanguageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) WithTimeout(timeout time.Duration) *CreateVMVolumeSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) WithContext(ctx context.Context) *CreateVMVolumeSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) WithHTTPClient(client *http.Client) *CreateVMVolumeSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentLanguage adds the contentLanguage to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) WithContentLanguage(contentLanguage *string) *CreateVMVolumeSnapshotParams {
	o.SetContentLanguage(contentLanguage)
	return o
}

// SetContentLanguage adds the contentLanguage to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) SetContentLanguage(contentLanguage *string) {
	o.ContentLanguage = contentLanguage
}

// WithRequestBody adds the requestBody to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) WithRequestBody(requestBody []*models.VMVolumeSnapshotCreationParams) *CreateVMVolumeSnapshotParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the create Vm volume snapshot params
func (o *CreateVMVolumeSnapshotParams) SetRequestBody(requestBody []*models.VMVolumeSnapshotCreationParams) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVMVolumeSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentLanguage != nil {

		// header param content-language
		if err := r.SetHeaderParam("content-language", *o.ContentLanguage); err != nil {
			return err
		}
	}
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
