// Code generated by go-swagger; DO NOT EDIT.

package virtual_private_cloud_route_table

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// NewUpdateVirtualPrivateCloudRouteTableParams creates a new UpdateVirtualPrivateCloudRouteTableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateVirtualPrivateCloudRouteTableParams() *UpdateVirtualPrivateCloudRouteTableParams {
	return &UpdateVirtualPrivateCloudRouteTableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateVirtualPrivateCloudRouteTableParamsWithTimeout creates a new UpdateVirtualPrivateCloudRouteTableParams object
// with the ability to set a timeout on a request.
func NewUpdateVirtualPrivateCloudRouteTableParamsWithTimeout(timeout time.Duration) *UpdateVirtualPrivateCloudRouteTableParams {
	return &UpdateVirtualPrivateCloudRouteTableParams{
		timeout: timeout,
	}
}

// NewUpdateVirtualPrivateCloudRouteTableParamsWithContext creates a new UpdateVirtualPrivateCloudRouteTableParams object
// with the ability to set a context for a request.
func NewUpdateVirtualPrivateCloudRouteTableParamsWithContext(ctx context.Context) *UpdateVirtualPrivateCloudRouteTableParams {
	return &UpdateVirtualPrivateCloudRouteTableParams{
		Context: ctx,
	}
}

// NewUpdateVirtualPrivateCloudRouteTableParamsWithHTTPClient creates a new UpdateVirtualPrivateCloudRouteTableParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateVirtualPrivateCloudRouteTableParamsWithHTTPClient(client *http.Client) *UpdateVirtualPrivateCloudRouteTableParams {
	return &UpdateVirtualPrivateCloudRouteTableParams{
		HTTPClient: client,
	}
}

/* UpdateVirtualPrivateCloudRouteTableParams contains all the parameters to send to the API endpoint
   for the update virtual private cloud route table operation.

   Typically these are written to a http.Request.
*/
type UpdateVirtualPrivateCloudRouteTableParams struct {

	// ContentLanguage.
	//
	// Default: "en-US"
	ContentLanguage *string

	// RequestBody.
	RequestBody *models.VirtualPrivateCloudRouteTableUpdationParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update virtual private cloud route table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateVirtualPrivateCloudRouteTableParams) WithDefaults() *UpdateVirtualPrivateCloudRouteTableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update virtual private cloud route table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateVirtualPrivateCloudRouteTableParams) SetDefaults() {
	var (
		contentLanguageDefault = string("en-US")
	)

	val := UpdateVirtualPrivateCloudRouteTableParams{
		ContentLanguage: &contentLanguageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) WithTimeout(timeout time.Duration) *UpdateVirtualPrivateCloudRouteTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) WithContext(ctx context.Context) *UpdateVirtualPrivateCloudRouteTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) WithHTTPClient(client *http.Client) *UpdateVirtualPrivateCloudRouteTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentLanguage adds the contentLanguage to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) WithContentLanguage(contentLanguage *string) *UpdateVirtualPrivateCloudRouteTableParams {
	o.SetContentLanguage(contentLanguage)
	return o
}

// SetContentLanguage adds the contentLanguage to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) SetContentLanguage(contentLanguage *string) {
	o.ContentLanguage = contentLanguage
}

// WithRequestBody adds the requestBody to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) WithRequestBody(requestBody *models.VirtualPrivateCloudRouteTableUpdationParams) *UpdateVirtualPrivateCloudRouteTableParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the update virtual private cloud route table params
func (o *UpdateVirtualPrivateCloudRouteTableParams) SetRequestBody(requestBody *models.VirtualPrivateCloudRouteTableUpdationParams) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateVirtualPrivateCloudRouteTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentLanguage != nil {

		// header param content-language
		if err := r.SetHeaderParam("content-language", *o.ContentLanguage); err != nil {
			return err
		}
	}
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
