// Code generated by go-swagger; DO NOT EDIT.

package content_library_image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// NewImportContentLibraryImageParams creates a new ImportContentLibraryImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewImportContentLibraryImageParams() *ImportContentLibraryImageParams {
	return &ImportContentLibraryImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewImportContentLibraryImageParamsWithTimeout creates a new ImportContentLibraryImageParams object
// with the ability to set a timeout on a request.
func NewImportContentLibraryImageParamsWithTimeout(timeout time.Duration) *ImportContentLibraryImageParams {
	return &ImportContentLibraryImageParams{
		timeout: timeout,
	}
}

// NewImportContentLibraryImageParamsWithContext creates a new ImportContentLibraryImageParams object
// with the ability to set a context for a request.
func NewImportContentLibraryImageParamsWithContext(ctx context.Context) *ImportContentLibraryImageParams {
	return &ImportContentLibraryImageParams{
		Context: ctx,
	}
}

// NewImportContentLibraryImageParamsWithHTTPClient creates a new ImportContentLibraryImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewImportContentLibraryImageParamsWithHTTPClient(client *http.Client) *ImportContentLibraryImageParams {
	return &ImportContentLibraryImageParams{
		HTTPClient: client,
	}
}

/* ImportContentLibraryImageParams contains all the parameters to send to the API endpoint
   for the import content library image operation.

   Typically these are written to a http.Request.
*/
type ImportContentLibraryImageParams struct {

	// ContentLanguage.
	//
	// Default: "en-US"
	ContentLanguage *string

	// RequestBody.
	RequestBody *models.ContentLibraryImageImportParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the import content library image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportContentLibraryImageParams) WithDefaults() *ImportContentLibraryImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the import content library image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ImportContentLibraryImageParams) SetDefaults() {
	var (
		contentLanguageDefault = string("en-US")
	)

	val := ImportContentLibraryImageParams{
		ContentLanguage: &contentLanguageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the import content library image params
func (o *ImportContentLibraryImageParams) WithTimeout(timeout time.Duration) *ImportContentLibraryImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the import content library image params
func (o *ImportContentLibraryImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the import content library image params
func (o *ImportContentLibraryImageParams) WithContext(ctx context.Context) *ImportContentLibraryImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the import content library image params
func (o *ImportContentLibraryImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the import content library image params
func (o *ImportContentLibraryImageParams) WithHTTPClient(client *http.Client) *ImportContentLibraryImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the import content library image params
func (o *ImportContentLibraryImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentLanguage adds the contentLanguage to the import content library image params
func (o *ImportContentLibraryImageParams) WithContentLanguage(contentLanguage *string) *ImportContentLibraryImageParams {
	o.SetContentLanguage(contentLanguage)
	return o
}

// SetContentLanguage adds the contentLanguage to the import content library image params
func (o *ImportContentLibraryImageParams) SetContentLanguage(contentLanguage *string) {
	o.ContentLanguage = contentLanguage
}

// WithRequestBody adds the requestBody to the import content library image params
func (o *ImportContentLibraryImageParams) WithRequestBody(requestBody *models.ContentLibraryImageImportParams) *ImportContentLibraryImageParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the import content library image params
func (o *ImportContentLibraryImageParams) SetRequestBody(requestBody *models.ContentLibraryImageImportParams) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *ImportContentLibraryImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentLanguage != nil {

		// header param content-language
		if err := r.SetHeaderParam("content-language", *o.ContentLanguage); err != nil {
			return err
		}
	}
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
