// Code generated by go-swagger; DO NOT EDIT.

package svt_image

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// GetSvtImagesConnectionReader is a Reader for the GetSvtImagesConnection structure.
type GetSvtImagesConnectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSvtImagesConnectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSvtImagesConnectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSvtImagesConnectionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetSvtImagesConnectionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetSvtImagesConnectionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSvtImagesConnectionOK creates a GetSvtImagesConnectionOK with default headers values
func NewGetSvtImagesConnectionOK() *GetSvtImagesConnectionOK {
	return &GetSvtImagesConnectionOK{}
}

/* GetSvtImagesConnectionOK describes a response with status code 200, with default header values.

GetSvtImagesConnectionOK get svt images connection o k
*/
type GetSvtImagesConnectionOK struct {
	XTowerRequestID string

	Payload *models.SvtImageConnection
}

func (o *GetSvtImagesConnectionOK) Error() string {
	return fmt.Sprintf("[POST /get-svt-images-connection][%d] getSvtImagesConnectionOK  %+v", 200, o.Payload)
}
func (o *GetSvtImagesConnectionOK) GetPayload() *models.SvtImageConnection {
	return o.Payload
}

func (o *GetSvtImagesConnectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.SvtImageConnection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSvtImagesConnectionBadRequest creates a GetSvtImagesConnectionBadRequest with default headers values
func NewGetSvtImagesConnectionBadRequest() *GetSvtImagesConnectionBadRequest {
	return &GetSvtImagesConnectionBadRequest{}
}

/* GetSvtImagesConnectionBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetSvtImagesConnectionBadRequest struct {
	XTowerRequestID string

	Payload *models.ErrorBody
}

func (o *GetSvtImagesConnectionBadRequest) Error() string {
	return fmt.Sprintf("[POST /get-svt-images-connection][%d] getSvtImagesConnectionBadRequest  %+v", 400, o.Payload)
}
func (o *GetSvtImagesConnectionBadRequest) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetSvtImagesConnectionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSvtImagesConnectionNotFound creates a GetSvtImagesConnectionNotFound with default headers values
func NewGetSvtImagesConnectionNotFound() *GetSvtImagesConnectionNotFound {
	return &GetSvtImagesConnectionNotFound{}
}

/* GetSvtImagesConnectionNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetSvtImagesConnectionNotFound struct {
	XTowerRequestID string

	Payload *models.ErrorBody
}

func (o *GetSvtImagesConnectionNotFound) Error() string {
	return fmt.Sprintf("[POST /get-svt-images-connection][%d] getSvtImagesConnectionNotFound  %+v", 404, o.Payload)
}
func (o *GetSvtImagesConnectionNotFound) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetSvtImagesConnectionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSvtImagesConnectionInternalServerError creates a GetSvtImagesConnectionInternalServerError with default headers values
func NewGetSvtImagesConnectionInternalServerError() *GetSvtImagesConnectionInternalServerError {
	return &GetSvtImagesConnectionInternalServerError{}
}

/* GetSvtImagesConnectionInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type GetSvtImagesConnectionInternalServerError struct {
	XTowerRequestID string

	Payload *models.ErrorBody
}

func (o *GetSvtImagesConnectionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /get-svt-images-connection][%d] getSvtImagesConnectionInternalServerError  %+v", 500, o.Payload)
}
func (o *GetSvtImagesConnectionInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetSvtImagesConnectionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
