// Code generated by go-swagger; DO NOT EDIT.

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/models"
)

// NewGetWitnessMetricsParams creates a new GetWitnessMetricsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWitnessMetricsParams() *GetWitnessMetricsParams {
	return &GetWitnessMetricsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetWitnessMetricsParamsWithTimeout creates a new GetWitnessMetricsParams object
// with the ability to set a timeout on a request.
func NewGetWitnessMetricsParamsWithTimeout(timeout time.Duration) *GetWitnessMetricsParams {
	return &GetWitnessMetricsParams{
		timeout: timeout,
	}
}

// NewGetWitnessMetricsParamsWithContext creates a new GetWitnessMetricsParams object
// with the ability to set a context for a request.
func NewGetWitnessMetricsParamsWithContext(ctx context.Context) *GetWitnessMetricsParams {
	return &GetWitnessMetricsParams{
		Context: ctx,
	}
}

// NewGetWitnessMetricsParamsWithHTTPClient creates a new GetWitnessMetricsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWitnessMetricsParamsWithHTTPClient(client *http.Client) *GetWitnessMetricsParams {
	return &GetWitnessMetricsParams{
		HTTPClient: client,
	}
}

/* GetWitnessMetricsParams contains all the parameters to send to the API endpoint
   for the get witness metrics operation.

   Typically these are written to a http.Request.
*/
type GetWitnessMetricsParams struct {

	// RequestBody.
	RequestBody *models.GetWitnessMetricInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get witness metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWitnessMetricsParams) WithDefaults() *GetWitnessMetricsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get witness metrics params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWitnessMetricsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get witness metrics params
func (o *GetWitnessMetricsParams) WithTimeout(timeout time.Duration) *GetWitnessMetricsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get witness metrics params
func (o *GetWitnessMetricsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get witness metrics params
func (o *GetWitnessMetricsParams) WithContext(ctx context.Context) *GetWitnessMetricsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get witness metrics params
func (o *GetWitnessMetricsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get witness metrics params
func (o *GetWitnessMetricsParams) WithHTTPClient(client *http.Client) *GetWitnessMetricsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get witness metrics params
func (o *GetWitnessMetricsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequestBody adds the requestBody to the get witness metrics params
func (o *GetWitnessMetricsParams) WithRequestBody(requestBody *models.GetWitnessMetricInput) *GetWitnessMetricsParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the get witness metrics params
func (o *GetWitnessMetricsParams) SetRequestBody(requestBody *models.GetWitnessMetricInput) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *GetWitnessMetricsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
