// Code generated by go-swagger; DO NOT EDIT.

package everoute_package

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new everoute package API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for everoute package API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetEveroutePackages(params *GetEveroutePackagesParams, opts ...ClientOption) (*GetEveroutePackagesOK, error)

	GetEveroutePackagesConnection(params *GetEveroutePackagesConnectionParams, opts ...ClientOption) (*GetEveroutePackagesConnectionOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetEveroutePackages get everoute packages API
*/
func (a *Client) GetEveroutePackages(params *GetEveroutePackagesParams, opts ...ClientOption) (*GetEveroutePackagesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEveroutePackagesParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetEveroutePackages",
		Method:             "POST",
		PathPattern:        "/get-everoute-packages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetEveroutePackagesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetEveroutePackagesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetEveroutePackages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetEveroutePackagesConnection get everoute packages connection API
*/
func (a *Client) GetEveroutePackagesConnection(params *GetEveroutePackagesConnectionParams, opts ...ClientOption) (*GetEveroutePackagesConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEveroutePackagesConnectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetEveroutePackagesConnection",
		Method:             "POST",
		PathPattern:        "/get-everoute-packages-connection",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetEveroutePackagesConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetEveroutePackagesConnectionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetEveroutePackagesConnection: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
