// Code generated by go-swagger; DO NOT EDIT.

package vm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// NewCreateVMFromContentLibraryTemplateBatchParams creates a new CreateVMFromContentLibraryTemplateBatchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateVMFromContentLibraryTemplateBatchParams() *CreateVMFromContentLibraryTemplateBatchParams {
	return &CreateVMFromContentLibraryTemplateBatchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateVMFromContentLibraryTemplateBatchParamsWithTimeout creates a new CreateVMFromContentLibraryTemplateBatchParams object
// with the ability to set a timeout on a request.
func NewCreateVMFromContentLibraryTemplateBatchParamsWithTimeout(timeout time.Duration) *CreateVMFromContentLibraryTemplateBatchParams {
	return &CreateVMFromContentLibraryTemplateBatchParams{
		timeout: timeout,
	}
}

// NewCreateVMFromContentLibraryTemplateBatchParamsWithContext creates a new CreateVMFromContentLibraryTemplateBatchParams object
// with the ability to set a context for a request.
func NewCreateVMFromContentLibraryTemplateBatchParamsWithContext(ctx context.Context) *CreateVMFromContentLibraryTemplateBatchParams {
	return &CreateVMFromContentLibraryTemplateBatchParams{
		Context: ctx,
	}
}

// NewCreateVMFromContentLibraryTemplateBatchParamsWithHTTPClient creates a new CreateVMFromContentLibraryTemplateBatchParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateVMFromContentLibraryTemplateBatchParamsWithHTTPClient(client *http.Client) *CreateVMFromContentLibraryTemplateBatchParams {
	return &CreateVMFromContentLibraryTemplateBatchParams{
		HTTPClient: client,
	}
}

/* CreateVMFromContentLibraryTemplateBatchParams contains all the parameters to send to the API endpoint
   for the create Vm from content library template batch operation.

   Typically these are written to a http.Request.
*/
type CreateVMFromContentLibraryTemplateBatchParams struct {

	// ContentLanguage.
	//
	// Default: "en-US"
	ContentLanguage *string

	// RequestBody.
	RequestBody *models.VMCreateVMFromContentLibraryTemplateBatchParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create Vm from content library template batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMFromContentLibraryTemplateBatchParams) WithDefaults() *CreateVMFromContentLibraryTemplateBatchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create Vm from content library template batch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateVMFromContentLibraryTemplateBatchParams) SetDefaults() {
	var (
		contentLanguageDefault = string("en-US")
	)

	val := CreateVMFromContentLibraryTemplateBatchParams{
		ContentLanguage: &contentLanguageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) WithTimeout(timeout time.Duration) *CreateVMFromContentLibraryTemplateBatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) WithContext(ctx context.Context) *CreateVMFromContentLibraryTemplateBatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) WithHTTPClient(client *http.Client) *CreateVMFromContentLibraryTemplateBatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContentLanguage adds the contentLanguage to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) WithContentLanguage(contentLanguage *string) *CreateVMFromContentLibraryTemplateBatchParams {
	o.SetContentLanguage(contentLanguage)
	return o
}

// SetContentLanguage adds the contentLanguage to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) SetContentLanguage(contentLanguage *string) {
	o.ContentLanguage = contentLanguage
}

// WithRequestBody adds the requestBody to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) WithRequestBody(requestBody *models.VMCreateVMFromContentLibraryTemplateBatchParams) *CreateVMFromContentLibraryTemplateBatchParams {
	o.SetRequestBody(requestBody)
	return o
}

// SetRequestBody adds the requestBody to the create Vm from content library template batch params
func (o *CreateVMFromContentLibraryTemplateBatchParams) SetRequestBody(requestBody *models.VMCreateVMFromContentLibraryTemplateBatchParams) {
	o.RequestBody = requestBody
}

// WriteToRequest writes these params to a swagger request
func (o *CreateVMFromContentLibraryTemplateBatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContentLanguage != nil {

		// header param content-language
		if err := r.SetHeaderParam("content-language", *o.ContentLanguage); err != nil {
			return err
		}
	}
	if o.RequestBody != nil {
		if err := r.SetBodyParam(o.RequestBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
