// Code generated by go-swagger; DO NOT EDIT.

package backup_target_execution

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/smartxworks/cloudtower-go-sdk/v2/models"
)

// GetBackupTargetExecutionsConnectionReader is a Reader for the GetBackupTargetExecutionsConnection structure.
type GetBackupTargetExecutionsConnectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBackupTargetExecutionsConnectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBackupTargetExecutionsConnectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, models.NewUnexpectedError(response, err)
		}
		return result, nil
	case 400:
		result := NewGetBackupTargetExecutionsConnectionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, models.NewUnexpectedError(response, err)
		}
		return nil, result
	case 404:
		result := NewGetBackupTargetExecutionsConnectionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, models.NewUnexpectedError(response, err)
		}
		return nil, result
	case 500:
		result := NewGetBackupTargetExecutionsConnectionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, models.NewUnexpectedError(response, err)
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBackupTargetExecutionsConnectionOK creates a GetBackupTargetExecutionsConnectionOK with default headers values
func NewGetBackupTargetExecutionsConnectionOK() *GetBackupTargetExecutionsConnectionOK {
	return &GetBackupTargetExecutionsConnectionOK{}
}

/* GetBackupTargetExecutionsConnectionOK describes a response with status code 200, with default header values.

GetBackupTargetExecutionsConnectionOK get backup target executions connection o k
*/
type GetBackupTargetExecutionsConnectionOK struct {
	XTowerRequestID string

	Payload *models.BackupTargetExecutionConnection
}

func (o *GetBackupTargetExecutionsConnectionOK) Error() string {
	return fmt.Sprintf("[POST /get-backup-target-executions-connection][%d] getBackupTargetExecutionsConnectionOK  %+v", 200, o.Payload)
}
func (o *GetBackupTargetExecutionsConnectionOK) GetPayload() *models.BackupTargetExecutionConnection {
	return o.Payload
}

func (o *GetBackupTargetExecutionsConnectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.BackupTargetExecutionConnection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupTargetExecutionsConnectionBadRequest creates a GetBackupTargetExecutionsConnectionBadRequest with default headers values
func NewGetBackupTargetExecutionsConnectionBadRequest() *GetBackupTargetExecutionsConnectionBadRequest {
	return &GetBackupTargetExecutionsConnectionBadRequest{}
}

/* GetBackupTargetExecutionsConnectionBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetBackupTargetExecutionsConnectionBadRequest struct {
	XTowerRequestID string

	Payload *models.ErrorBody
}

func (o *GetBackupTargetExecutionsConnectionBadRequest) Error() string {
	return fmt.Sprintf("[POST /get-backup-target-executions-connection][%d] getBackupTargetExecutionsConnectionBadRequest  %+v", 400, o.Payload)
}
func (o *GetBackupTargetExecutionsConnectionBadRequest) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetBackupTargetExecutionsConnectionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupTargetExecutionsConnectionNotFound creates a GetBackupTargetExecutionsConnectionNotFound with default headers values
func NewGetBackupTargetExecutionsConnectionNotFound() *GetBackupTargetExecutionsConnectionNotFound {
	return &GetBackupTargetExecutionsConnectionNotFound{}
}

/* GetBackupTargetExecutionsConnectionNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetBackupTargetExecutionsConnectionNotFound struct {
	XTowerRequestID string

	Payload *models.ErrorBody
}

func (o *GetBackupTargetExecutionsConnectionNotFound) Error() string {
	return fmt.Sprintf("[POST /get-backup-target-executions-connection][%d] getBackupTargetExecutionsConnectionNotFound  %+v", 404, o.Payload)
}
func (o *GetBackupTargetExecutionsConnectionNotFound) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetBackupTargetExecutionsConnectionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBackupTargetExecutionsConnectionInternalServerError creates a GetBackupTargetExecutionsConnectionInternalServerError with default headers values
func NewGetBackupTargetExecutionsConnectionInternalServerError() *GetBackupTargetExecutionsConnectionInternalServerError {
	return &GetBackupTargetExecutionsConnectionInternalServerError{}
}

/* GetBackupTargetExecutionsConnectionInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type GetBackupTargetExecutionsConnectionInternalServerError struct {
	XTowerRequestID string

	Payload *models.ErrorBody
}

func (o *GetBackupTargetExecutionsConnectionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /get-backup-target-executions-connection][%d] getBackupTargetExecutionsConnectionInternalServerError  %+v", 500, o.Payload)
}
func (o *GetBackupTargetExecutionsConnectionInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetBackupTargetExecutionsConnectionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header x-tower-request-id
	hdrXTowerRequestID := response.GetHeader("x-tower-request-id")

	if hdrXTowerRequestID != "" {
		o.XTowerRequestID = hdrXTowerRequestID
	}

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
