// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NestedEverouteClusterAgentStatus nested everoute cluster agent status
//
// swagger:model NestedEverouteClusterAgentStatus
type NestedEverouteClusterAgentStatus struct {

	// current number
	CurrentNumber *int32 `json:"currentNumber,omitempty"`

	// expect number
	ExpectNumber *int32 `json:"expectNumber,omitempty"`

	// instances
	Instances []*NestedEverouteAgentStatus `json:"instances,omitempty"`

	// manage v d ses
	ManageVDSes []*NestedEverouteManageVDSStatus `json:"manageVDSes,omitempty"`

	// number health
	NumberHealth *int32 `json:"numberHealth,omitempty"`
}

// Validate validates this nested everoute cluster agent status
func (m *NestedEverouteClusterAgentStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInstances(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateManageVDSes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NestedEverouteClusterAgentStatus) validateInstances(formats strfmt.Registry) error {
	if swag.IsZero(m.Instances) { // not required
		return nil
	}

	for i := 0; i < len(m.Instances); i++ {
		if swag.IsZero(m.Instances[i]) { // not required
			continue
		}

		if m.Instances[i] != nil {
			if err := m.Instances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("instances" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("instances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NestedEverouteClusterAgentStatus) validateManageVDSes(formats strfmt.Registry) error {
	if swag.IsZero(m.ManageVDSes) { // not required
		return nil
	}

	for i := 0; i < len(m.ManageVDSes); i++ {
		if swag.IsZero(m.ManageVDSes[i]) { // not required
			continue
		}

		if m.ManageVDSes[i] != nil {
			if err := m.ManageVDSes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("manageVDSes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("manageVDSes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this nested everoute cluster agent status based on the context it is used
func (m *NestedEverouteClusterAgentStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInstances(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateManageVDSes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NestedEverouteClusterAgentStatus) contextValidateInstances(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Instances); i++ {

		if m.Instances[i] != nil {
			if err := m.Instances[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("instances" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("instances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *NestedEverouteClusterAgentStatus) contextValidateManageVDSes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ManageVDSes); i++ {

		if m.ManageVDSes[i] != nil {
			if err := m.ManageVDSes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("manageVDSes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("manageVDSes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *NestedEverouteClusterAgentStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NestedEverouteClusterAgentStatus) UnmarshalBinary(b []byte) error {
	var res NestedEverouteClusterAgentStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
